### ISSUE TITLE
Greater visibility into the background build process would lead to fewer surprises for lorri users

### ISSUE THREAD

**Issue by exarkun** [nix-community/lorri#77]
**Feature description**

Lorri helpfully re-builds the shell derivation on demand in the background when necessary.  This provides a very streamlined user experience where the work to change the shell derivation expression itself is the trigger to update the environment - rather than requiring users take an extra step after changing the expression to build and activate the expression.

However, by doing this work implicitly in the background one thing is lost - explicit notification to the user about when a build starts and stops and whether it succeeds or fails.

Lorri should preserve the best parts of both workflows and deliver this information to users about the background builds it performs.

One way Lorri could do this (eg, in bash) is to take control of part of the shell prompt and present the information there.

For example, for a prompt displayed when the current environment is considered up-to-date with respect to shell.nix, instead of the usual prompt, Lorri could arrange for the prompt to be:

```
[✅ exarkun@magnon:~]$
```

If the prompt is displayed while Lorri is performing a build:

```
[🏗 exarkun@magnon:~]$
```

And quite importantly, if a prompt is displayed after a build attempted by Lorri has *failed*:

```
[⚠️ exarkun@magnon:~]$
```

Of course, the unicode is cute but this information could easily be conveyed with short ASCII-only words instead.  Other variations might be to display the time since the last successful build or some kind of generation counter (though I believe an explicit "something has failed, your environment is stale, it will remain stale until you fix it" indicator would be very valuable). 

**Target users**

This will help all Lorri end-users by giving them more complete information about the state of their environment.

**Comment by nyarly** [comment]
Lorri already has a feature wherein it can report its internal state.

In my shell, I use a function based on `lorri internal__stream_events --kind snapshot` to determine what's happening when the prompt is rendered. 

At various times, I've also run a little service that consumed the live stream (i.e. without `--kind`) and issued libnotify messages when builds completed.

**Comment by nyarly** [comment]
@exarhun Did that addess you issue?

**Comment by exarkun** [comment]
Nope.  I was looking for something that is more of an end-user experience rather than pieces for building my own (esp. since it sounds like perhaps the pieces are there and someone just needs to assemble them for lazy folks like myself).

**Comment by keysmashes** [comment]
I use the following config block for [starship](https://starship.rs/), which prints a 🚛 whenever lorri's active, followed by ⌛ if it's currently building or ❌ if the last build failed:

```toml
[custom.lorri]
command = "timeout 1 lorri internal stream-events --kind snapshot | jq -r --arg pwd \"$PWD\" 'if .[keys[0]].nix_file | startswith($pwd + \"/\") then {Completed: \"\", Started: \"⌛\", Failure: \"❌\"}[keys[0]] else \"\" end' "
description = "Whether lorri has finished evaluation yet"
format = "with [$symbol($output) ]($style)"
shell = "sh"
symbol = "🚛"
when = "test -v IN_LORRI_SHELL"
```

though I get a log line in journalctl every time the prompt is evaluated saying `INFO build status, message: NewListener(Sender { .. })`, which is mildly unnerving and I wonder if it's related to #82 at all.
